# Generated by Django 3.1.2 on 2020-10-05 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='third_party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('third_party_id', models.IntegerField(verbose_name='third_party_id')),
                ('first_name', models.CharField(max_length=128, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=128, verbose_name='last_name')),
                ('patronymic', models.CharField(blank=True, max_length=128, verbose_name='patronymic')),
                ('birth_date', models.DateField(verbose_name='birth_date')),
            ],
        ),
        migrations.CreateModel(
            name='accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField(verbose_name='account_id')),
                ('account_number', models.CharField(max_length=512, verbose_name='account_number')),
                ('start_date', models.DateField(verbose_name='start_date')),
                ('end_date', models.DateField(verbose_name='end_date')),
                ('third_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskapp.third_party')),
            ],
        ),
    ]
