# Generated by Django 3.1.2 on 2020-10-05 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='account_id',
        ),
        migrations.RemoveField(
            model_name='third_party',
            name='third_party_id',
        ),
    ]
